### ISSUE TITLE
ExperimentHub() timeout error

### ISSUE THREAD

**Issue by xingrenUB** [Bioconductor/ExperimentHub#10]
library(ExperimentHub)
ehub <- ExperimentHub()

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [experimenthub.bioconductor.org] Connection timed out after 10000 milliseconds

I also could not open experimenthub.bioconductor.org in the browser.

**Comment by lshep** [comment]
We have been experiencing intermittent inactivity. We are looking into the issue. But please try again at a later time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lshep** [comment]
There was an issue with the AWS host instance that stores the database.  This should be resolved.

**Comment by Yabous** [comment]
I've tried repeatedly to download the GDP indicator from World bank's wbstats package in R. It returns the following message:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [api.worldbank.org] Operation timed out after 20011 milliseconds with 195586 out of 3625865 bytes received

How to fix this error please?

**Comment by lshep** [comment]
I don't think this is an ExperimentHub issue but an R / download issue since you do not indicate you are using ExperimentHub interface.  However,  download.file changes its default timeout limit to 60 second. My guess is, if you change the default timeout limit the download would complete since the error indicates the download started and was only a partial download.   `options(timeout=xxx)`  where xxx is a time in seconds for the default timeout.
