### ISSUE TITLE
Documentation for `...` in ExperimentHub constructor missing? 

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/ExperimentHub#16]
Hi Lori @lshep, Martin @mtmorgan 

Is the use of the elipsis (`...`) documented somewhere? I don't see it in `?ExperimentHub::ExperimentHub`?
Is it ignored? 

Thanks!

**Comment by lshep** [comment]
I  have a sticky to go over creating hub packages and adding resources to the hubs I'll make it more generally to review all documentation.   
The  `...`  is passed down into `.Hub() and then to `new()` . The ExperimentHub and AnnotationHub are extensions of the Virtual Hub class.  I think it is currently ignored since all values of the hub class get defined but is needed for the placeholder value of .db_index that gets defined/overwritten later.

**Comment by lshep** [comment]
https://github.com/Bioconductor/ExperimentHub/commit/e6a4b73961a7d4aaef955e924164961c2e40b7e8
